/** @type {import('next').NextConfig} */
const nextConfig = {
  webpack: (config) => {
    config.module.rules.push({
      test: /\.css$/i,
      use: [
        {
          loader: 'style-loader',
          options: { injectType: 'singletonStyleTag' }
        },
        {
          loader: 'css-loader',
          options: {
            modules: {
              auto: true,
              localIdentName: '[name]__[local]--[hash:base64:5]',
            },
          },
        },
        'postcss-loader', // Add this for Tailwind support
      ],
    });
    return config;
  },
};

export default nextConfig;





import "./globals.css";



export const metadata = {
  title: "AAS Information Technology | Innovative IT Solutions",
  description: "AAS Information Technology delivers cutting-edge software solutions, web development, and IT consulting services tailored to drive business success.",
  keywords: "IT solutions, software development, web development, IT consulting, AAS Information Technology",
  author: "AAS Information Technology",
  robots: "index, follow",
  openGraph: {
    title: "AAS Information Technology | Innovative IT Solutions",
    description: "Empowering businesses with state-of-the-art IT solutions, including web development, mobile apps, and cloud services.",
    type: "website",
    url: "https://www.aasinfotech.com", // Replace with your actual website URL
    images: [
      {
        url: "https://www.aasinfotech.com/og-image.jpg", // Replace with your OG image URL
        width: 1200,
        height: 630,
        alt: "AAS Information Technology - Innovative IT Solutions",
      },
    ],
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
      
      >
        {children}
      </body>
    </html>
  );
}





import "./globals.css";
import { ToastContainer } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css'; // Import the CSS for toasts globally
import { Provider } from "react-redux";
import store from "@/redux/store";
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {

  return (
    <html lang="en">
      <body
       
      >
        

              
        <ToastContainer position="top-right" autoClose={3000} hideProgressBar closeButton />
           <Provider store={store} >
              {children}
            </Provider>  
           
        
      </body>
    </html>
  );
}

{
  "name": "client",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "dev": "next dev --turbopack",
    "build": "next build",
    "start": "next start",
    "lint": "next lint"
  },
  "dependencies": {
    "@emotion/react": "^11.14.0",
    "@emotion/styled": "^11.14.0",
    "@fortawesome/free-solid-svg-icons": "^6.7.2",
    "@fortawesome/react-fontawesome": "^0.2.2",
    "@heroicons/react": "^2.2.0",
    "@mui/icons-material": "^6.4.4",
    "@mui/material": "^6.4.4",
    "@radix-ui/react-accordion": "^1.2.3",
    "@radix-ui/react-avatar": "^1.1.3",
    "@radix-ui/react-checkbox": "^1.1.4",
    "@radix-ui/react-collapsible": "^1.1.3",
    "@radix-ui/react-dialog": "^1.1.6",
    "@radix-ui/react-dropdown-menu": "^2.1.6",
    "@radix-ui/react-label": "^2.1.2",
    "@radix-ui/react-navigation-menu": "^1.2.5",
    "@radix-ui/react-select": "^2.1.6",
    "@radix-ui/react-separator": "^1.1.2",
    "@radix-ui/react-slot": "^1.1.2",
    "@radix-ui/react-toast": "^1.2.6",
    "@radix-ui/react-tooltip": "^1.1.8",
    "@reduxjs/toolkit": "^2.5.1",
    "@tabler/icons-react": "^3.30.0",
    "axios": "^1.7.9",
    "class-variance-authority": "^0.7.1",
    "clsx": "^2.1.1",
    "embla-carousel-react": "^8.5.2",
    "fortawesome": "^0.0.1-security",
    "gsap": "^3.12.7",
    "heroicons": "^2.2.0",
    "locomotive-scroll": "^4.1.4",
    "lucide-react": "^0.475.0",
    "mini-svg-data-uri": "^1.4.4",
    "motion": "^12.4.3",
    "next": "15.1.7",
    "next-themes": "^0.4.4",
    "react": "^19.0.0",
    "react-dom": "^19.0.0",
    "react-element-to-jsx-string": "^17.0.0",
    "react-icons": "^5.5.0",
    "react-ions": "^0.0.1",
    "react-redux": "^9.2.0",
    "react-toastify": "^11.0.3",
    "tailwind-merge": "^3.0.1",
    "tailwindcss-animate": "^1.0.7",
    "toastify": "^2.0.1"
  },
  "devDependencies": {
    "@eslint/eslintrc": "^3",
    "eslint": "^9",
    "eslint-config-next": "15.1.7",
    "postcss": "^8",
    "style-loader": "^4.0.0",
    "tailwindcss": "^3.4.1"
    
  }
}
