/** @type {import('next').NextConfig} */
const nextConfig = {
  webpack: (config) => {
    config.module.rules.push({
      test: /\.css$/i,
      use: [
        {
          loader: 'style-loader',
          options: { injectType: 'singletonStyleTag' }
        },
        {
          loader: 'css-loader',
          options: {
            modules: {
              auto: true,
              localIdentName: '[name]__[local]--[hash:base64:5]',
            },
          },
        },
        'postcss-loader', // Add this for Tailwind support
      ],
    });
    return config;
  },
};

export default nextConfig;





import "./globals.css";



export const metadata = {
  title: "AAS Information Technology | Innovative IT Solutions",
  description: "AAS Information Technology delivers cutting-edge software solutions, web development, and IT consulting services tailored to drive business success.",
  keywords: "IT solutions, software development, web development, IT consulting, AAS Information Technology",
  author: "AAS Information Technology",
  robots: "index, follow",
  openGraph: {
    title: "AAS Information Technology | Innovative IT Solutions",
    description: "Empowering businesses with state-of-the-art IT solutions, including web development, mobile apps, and cloud services.",
    type: "website",
    url: "https://www.aasinfotech.com", // Replace with your actual website URL
    images: [
      {
        url: "https://www.aasinfotech.com/og-image.jpg", // Replace with your OG image URL
        width: 1200,
        height: 630,
        alt: "AAS Information Technology - Innovative IT Solutions",
      },
    ],
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
      
      >
        {children}
      </body>
    </html>
  );
}





import "./globals.css";
import { ToastContainer } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css'; // Import the CSS for toasts globally
import { Provider } from "react-redux";
import store from "@/redux/store";
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {

  return (
    <html lang="en">
      <body
       
      >
        

              
        <ToastContainer position="top-right" autoClose={3000} hideProgressBar closeButton />
           <Provider store={store} >
              {children}
            </Provider>  
           
        
      </body>
    </html>
  );
}

