export const posts = [
  {
    id: 1,
    slug: 'how-to-start-a-blog',
    title: 'How to Start a Blog: A Complete Guide',
    excerpt: 'Starting a blog is easier than you think. Here’s a step-by-step guide to help you get started...',
    content: `Starting a blog is one of the best ways to share your thoughts, ideas, and expertise...`,
    publishedAt: '2025-02-15',
    likes: 12,
    imageUrl: 'https://images.pexels.com/photos/261662/pexels-photo-261662.jpeg?auto=compress&cs=tinysrgb&w=600',
  },
  {
    id: 2,
    slug: 'importance-of-seo',
    title: 'Why SEO is Crucial for Your Blog’s Success',
    excerpt: 'SEO (Search Engine Optimization) is an essential element of any successful blog...',
    content: `SEO (Search Engine Optimization) is the art and science of getting your website ranked higher on search engines...`,
    publishedAt: '2025-02-16',
    likes: 20,
    imageUrl: 'https://media.istockphoto.com/id/891297988/photo/seo-search-engine-optimization.jpg?b=1&s=612x612&w=0&k=20&c=YC_us3mf2Mx_ceMQXXut52My6f6JSkM6lmIzYxi_UWQ=',
  },
  {
    id: 1,
    slug: 'how-to-start-a-blog',
    title: 'How to Start a Blog: A Complete Guide',
    excerpt: 'Starting a blog is easier than you think. Here’s a step-by-step guide to help you get started...',
    content: `Starting a blog is one of the best ways to share your thoughts, ideas, and expertise...`,
    publishedAt: '2025-02-15',
    likes: 12,
    imageUrl: 'https://images.pexels.com/photos/261662/pexels-photo-261662.jpeg?auto=compress&cs=tinysrgb&w=600',
  },
  {
    id: 2,
    slug: 'importance-of-seo',
    title: 'Why SEO is Crucial for Your Blog’s Success',
    excerpt: 'SEO (Search Engine Optimization) is an essential element of any successful blog...',
    content: `SEO (Search Engine Optimization) is the art and science of getting your website ranked higher on search engines...`,
    publishedAt: '2025-02-16',
    likes: 20,
    imageUrl: 'https://media.istockphoto.com/id/891297988/photo/seo-search-engine-optimization.jpg?b=1&s=612x612&w=0&k=20&c=YC_us3mf2Mx_ceMQXXut52My6f6JSkM6lmIzYxi_UWQ=',
  },
  {
    id: 1,
    slug: 'how-to-start-a-blog',
    title: 'How to Start a Blog: A Complete Guide',
    excerpt: 'Starting a blog is easier than you think. Here’s a step-by-step guide to help you get started...',
    content: `Starting a blog is one of the best ways to share your thoughts, ideas, and expertise...`,
    publishedAt: '2025-02-15',
    likes: 12,
    imageUrl: 'https://images.pexels.com/photos/261662/pexels-photo-261662.jpeg?auto=compress&cs=tinysrgb&w=600',
  },
  {
    id: 2,
    slug: 'importance-of-seo',
    title: 'Why SEO is Crucial for Your Blog’s Success',
    excerpt: 'SEO (Search Engine Optimization) is an essential element of any successful blog...',
    content: `SEO (Search Engine Optimization) is the art and science of getting your website ranked higher on search engines...`,
    publishedAt: '2025-02-16',
    likes: 20,
    imageUrl: 'https://media.istockphoto.com/id/891297988/photo/seo-search-engine-optimization.jpg?b=1&s=612x612&w=0&k=20&c=YC_us3mf2Mx_ceMQXXut52My6f6JSkM6lmIzYxi_UWQ=',
  },
  {
    id: 1,
    slug: 'how-to-start-a-blog',
    title: 'How to Start a Blog: A Complete Guide',
    excerpt: 'Starting a blog is easier than you think. Here’s a step-by-step guide to help you get started...',
    content: `Starting a blog is one of the best ways to share your thoughts, ideas, and expertise...`,
    publishedAt: '2025-02-15',
    likes: 12,
    imageUrl: 'https://images.pexels.com/photos/261662/pexels-photo-261662.jpeg?auto=compress&cs=tinysrgb&w=600',
  },
  {
    id: 2,
    slug: 'importance-of-seo',
    title: 'Why SEO is Crucial for Your Blog’s Success',
    excerpt: 'SEO (Search Engine Optimization) is an essential element of any successful blog...',
    content: `SEO (Search Engine Optimization) is the art and science of getting your website ranked higher on search engines...`,
    publishedAt: '2025-02-16',
    likes: 20,
    imageUrl: 'https://media.istockphoto.com/id/891297988/photo/seo-search-engine-optimization.jpg?b=1&s=612x612&w=0&k=20&c=YC_us3mf2Mx_ceMQXXut52My6f6JSkM6lmIzYxi_UWQ=',
  },

  // {
  //   id: 8,
  //   slug: 'importance-of-seo',
  //   title: 'Why SEO is Crucial for Your Blog’s Success',
  //   excerpt: 'SEO (Search Engine Optimization) is an essential element of any successful blog...',
  //   content: `SEO (Search Engine Optimization) is the art and science of getting your website ranked higher on search engines...`,
  //   publishedAt: '2025-02-16',
  //   likes: 20,
  //   imageUrl: 'https://source.unsplash.com/600x400/?seo,search',
  // },
  // {
  //   id: 9,
  //   slug: 'importance-of-seo',
  //   title: 'Why SEO is Crucial for Your Blog’s Success',
  //   excerpt: 'SEO (Search Engine Optimization) is an essential element of any successful blog...',
  //   content: `SEO (Search Engine Optimization) is the art and science of getting your website ranked higher on search engines...`,
  //   publishedAt: '2025-02-16',
  //   likes: 20,
  //   imageUrl: 'https://source.unsplash.com/600x400/?seo,search',
  // },
  // {
  //   id: 10,
  //   slug: 'importance-of-seo',
  //   title: 'Why SEO is Crucial for Your Blog’s Success',
  //   excerpt: 'SEO (Search Engine Optimization) is an essential element of any successful blog...',
  //   content: `SEO (Search Engine Optimization) is the art and science of getting your website ranked higher on search engines...`,
  //   publishedAt: '2025-02-16',
  //   likes: 20,
  //   imageUrl: 'https://source.unsplash.com/600x400/?seo,search',
  // },
  // {
  //   id: 11,
  //   slug: 'importance-of-seo',
  //   title: 'Why SEO is Crucial for Your Blog’s Success',
  //   excerpt: 'SEO (Search Engine Optimization) is an essential element of any successful blog...',
  //   content: `SEO (Search Engine Optimization) is the art and science of getting your website ranked higher on search engines...`,
  //   publishedAt: '2025-02-16',
  //   likes: 20,
  //   imageUrl: 'https://source.unsplash.com/600x400/?seo,search',
  // },
  // {
  //   id: 12,
  //   slug: 'importance-of-seo',
  //   title: 'Why SEO is Crucial for Your Blog’s Success',
  //   excerpt: 'SEO (Search Engine Optimization) is an essential element of any successful blog...',
  //   content: `SEO (Search Engine Optimization) is the art and science of getting your website ranked higher on search engines...`,
  //   publishedAt: '2025-02-16',
  //   likes: 20,
  //   imageUrl: 'https://source.unsplash.com/600x400/?seo,search',
  // },
  // {
  //   id: 13,
  //   slug: 'importance-of-seo',
  //   title: 'Why SEO is Crucial for Your Blog’s Success',
  //   excerpt: 'SEO (Search Engine Optimization) is an essential element of any successful blog...',
  //   content: `SEO (Search Engine Optimization) is the art and science of getting your website ranked higher on search engines...`,
  //   publishedAt: '2025-02-16',
  //   likes: 20,
  //   imageUrl: 'https://source.unsplash.com/600x400/?seo,search',
  // },
  // {
  //   id: 14,
  //   slug: 'importance-of-seo',
  //   title: 'Why SEO is Crucial for Your Blog’s Success',
  //   excerpt: 'SEO (Search Engine Optimization) is an essential element of any successful blog...',
  //   content: `SEO (Search Engine Optimization) is the art and science of getting your website ranked higher on search engines...`,
  //   publishedAt: '2025-02-16',
  //   likes: 20,
  //   imageUrl: 'https://source.unsplash.com/600x400/?seo,search',
  // },
  // {
  //   id: 15,
  //   slug: 'top-blogging-tools',
  //   title: 'Top Blogging Tools You Need to Succeed',
  //   excerpt: 'Every successful blogger needs the right set of tools...',
  //   content: `When you start blogging, the right tools can make a world of difference...`,
  //   publishedAt: '2025-02-17',
  //   likes: 8,
  //   imageUrl: 'https://source.unsplash.com/600x400/?tools,blogging',
  // },
  // {
  //   id: 16,
  //   slug: 'top-blogging-tools',
  //   title: 'Top Blogging Tools You Need to Succeed',
  //   excerpt: 'Every successful blogger needs the right set of tools...',
  //   content: `When you start blogging, the right tools can make a world of difference...`,
  //   publishedAt: '2025-02-17',
  //   likes: 8,
  //   imageUrl: 'https://source.unsplash.com/600x400/?tools,blogging',
  // },
  // {
  //   id: 17,
  //   slug: 'top-blogging-tools',
  //   title: 'Top Blogging Tools You Need to Succeed',
  //   excerpt: 'Every successful blogger needs the right set of tools...',
  //   content: `When you start blogging, the right tools can make a world of difference...`,
  //   publishedAt: '2025-02-17',
  //   likes: 8,
  //   imageUrl: 'https://source.unsplash.com/600x400/?tools,blogging',
  // },
  // {
  //   id: 18,
  //   slug: 'top-blogging-tools',
  //   title: 'Top Blogging Tools You Need to Succeed',
  //   excerpt: 'Every successful blogger needs the right set of tools...',
  //   content: `When you start blogging, the right tools can make a world of difference...`,
  //   publishedAt: '2025-02-17',
  //   likes: 8,
  //   imageUrl: 'https://source.unsplash.com/600x400/?tools,blogging',
  // },
  // {
  //   id: 19,
  //   slug: 'top-blogging-tools',
  //   title: 'Top Blogging Tools You Need to Succeed',
  //   excerpt: 'Every successful blogger needs the right set of tools...',
  //   content: `When you start blogging, the right tools can make a world of difference...`,
  //   publishedAt: '2025-02-17',
  //   likes: 8,
  //   imageUrl: 'https://source.unsplash.com/600x400/?tools,blogging',
  // },
  // {
  //   id: 20,
  //   slug: 'top-blogging-tools',
  //   title: 'Top Blogging Tools You Need to Succeed',
  //   excerpt: 'Every successful blogger needs the right set of tools...',
  //   content: `When you start blogging, the right tools can make a world of difference...`,
  //   publishedAt: '2025-02-17',
  //   likes: 8,
  //   imageUrl: 'https://source.unsplash.com/600x400/?tools,blogging',
  // },
  // {
  //   id: 21,
  //   slug: 'top-blogging-tools',
  //   title: 'Top Blogging Tools You Need to Succeed',
  //   excerpt: 'Every successful blogger needs the right set of tools...',
  //   content: `When you start blogging, the right tools can make a world of difference...`,
  //   publishedAt: '2025-02-17',
  //   likes: 8,
  //   imageUrl: 'https://source.unsplash.com/600x400/?tools,blogging',
  // },
  // {
  //   id: 21,
  //   slug: 'top-blogging-tools',
  //   title: 'Top Blogging Tools You Need to Succeed',
  //   excerpt: 'Every successful blogger needs the right set of tools...',
  //   content: `When you start blogging, the right tools can make a world of difference...`,
  //   publishedAt: '2025-02-17',
  //   likes: 8,
  //   imageUrl: 'https://source.unsplash.com/600x400/?tools,blogging',
  // },
  // {
  //   id: 22,
  //   slug: 'top-blogging-tools',
  //   title: 'Top Blogging Tools You Need to Succeed',
  //   excerpt: 'Every successful blogger needs the right set of tools...',
  //   content: `When you start blogging, the right tools can make a world of difference...`,
  //   publishedAt: '2025-02-17',
  //   likes: 8,
  //   imageUrl: 'https://source.unsplash.com/600x400/?tools,blogging',
  // },
  // {
  //   id: 23,
  //   slug: 'top-blogging-tools',
  //   title: 'Top Blogging Tools You Need to Succeed',
  //   excerpt: 'Every successful blogger needs the right set of tools...',
  //   content: `When you start blogging, the right tools can make a world of difference...`,
  //   publishedAt: '2025-02-17',
  //   likes: 8,
  //   imageUrl: 'https://source.unsplash.com/600x400/?tools,blogging',
  // },
  // {
  //   id: 24,
  //   slug: 'top-blogging-tools',
  //   title: 'Top Blogging Tools You Need to Succeed',
  //   excerpt: 'Every successful blogger needs the right set of tools...',
  //   content: `When you start blogging, the right tools can make a world of difference...`,
  //   publishedAt: '2025-02-17',
  //   likes: 8,
  //   imageUrl: 'https://source.unsplash.com/600x400/?tools,blogging',
  // },
  // // Additional 22 blog posts...
  // {
  //   id: 25,
  //   slug: 'monetizing-your-blog',
  //   title: 'How to Monetize Your Blog and Make Money',
  //   excerpt: 'Monetizing your blog can be a great way to generate passive income...',
  //   content: `If you have a successful blog, there are many ways to monetize it...`,
  //   publishedAt: '2025-03-10',
  //   likes: 18,
  //   imageUrl: 'https://source.unsplash.com/600x400/?money,blogging',
  // },
];
